openapi: 3.0.0
info:
  title: Заказ на ресурсы облака
  version: 0.0.1
servers:
  - url: http://localhost:8080/api/v1/
    description: Dev server
paths:
  /clouds:
    get:
      summary: Метод получения списка ресурсов на облако
      tags:
        - Clouds
      operationId: getAllClouds
      responses:
        "200":
          description: Успешный ответ со списком ресурсов в облаке
          content:
            adplication/json:
              schema:
                $ref: "#/components/schemas/Clouds"
        "400":
          description: Серверу непонятен запрос
          content:
            adplication/json:
              schema:
                $ref: "#/components/schemas/Error400"
        "500":
          description: Внутренняя ошибка сервера
          content:
            adplication/json:
              schema:
                $ref: "#/components/schemas/Error500"
        "default":
          description: Все остальное
          content:
            adplication/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Метод создания заказа на облако
      tags :
        - Clouds
      operationId: createCloud
      requestBody:
        required: true
        content:
          adplication/json:
            schema:
              $ref: "#/components/schemas/Error"      
      responses:
        "200":
          description: Успешный ответ создания заказа на облако
          content:
            adplication/json:
              schema:
                $ref: "#/components/schemas/Cloud"
        "400":
          description: Серверу непонятен запрос
          content:
            adplication/json:
              schema:
                $ref: "#/components/schemas/Error400"
        "500":
          description: Внутренняя ошибка сервера
          content:
            adplication/json:
              schema:
                $ref: "#/components/schemas/Error500"
        "default" :
          description: Всё остальное
          content :
            adplication/json:
              schema:
                $ref: "#/components/schemas/Error"
  /clouds/{cloud_id}:
    get:
      summary: Метод получения заказа на облако по ID
      tags:
        - Clouds
      operationId: getCloudById
      parameters:
        - name: cloud_id
          in: path
          required: true
          description: Идентификатор заказа облака
          schema:
            type: string
          example: f102b615
      responses:
        "200":
           description: Успешный ответ заказом облака по ID
           content:
             adplication/json:
               schema:
                 $ref: "#/components/schemas/Cloud"
        "400":
          description: Серверу непонятен запрос
          content:
            adplication/json:
              schema:
                $ref: "#/components/schemas/Error400"
        "500":
          description: Внутренняя ошибка сервера
          content:
            adplication/json:
              schema:
                $ref: "#/components/schemas/Error500"
        "default":
           description: Все остальное
           content:
             adplication/json:
               schema:
                 $ref: "#/components/schemas/Error"
    delete:
      summary: Метод отмены заказа на облако по ID
      tags: 
        - Clouds
      operationId: cencelCloudById
      parameters:
       - name: cloud_id
         in: path
         required: true
         description: Идентификатор заказа облака
         schema:
           type: string
         example: f102b615
      responses:
        "200":
           description: Успешный ответ заказом облака по ID
           content:
             adplication/json: {}
        "400":
          description: Серверу непонятен запрос
          content:
            adplication/json:
              schema:
                $ref: "#/components/schemas/Error400"
        "500":
          description: Внутренняя ошибка сервера
          content:
            adplication/json:
              schema:
                $ref: "#/components/schemas/Error500"
        "default":
           description: Все остальное
           content:
             adplication/json:
               schema:
                 $ref: "#/components/schemas/Error"
components:
  schemas:
    Cloud:
      type: object
      required:
        - id_server
        - OS
        - RAM
      properties:
        cloud_id:
          type: string
          example: f102b615
        id_server:
          type: string
          example: f102b615
        OS:
          type: string
          enum:
            - Windows
            - Linux
          description: Операционная система сервера
        RAM:
          type: string
          example: 128
    Clouds:
      type: array
      items:
        $ref: "#/components/schemas/Cloud"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string
    Error400:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          example: 400
        message:
          type: string
    Error500:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          example: 500
        message:
          type: string